apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ci-helper-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci-helper-app
    app.kubernetes.io/part-of: ci-helper-app
  name: ci-helper-app
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ci-helper-app
      app.kubernetes.io/instance: ci-helper-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ci-helper-app
        app.kubernetes.io/instance: ci-helper-app
    spec:
      containers:
      - image: ci-helper-app:latest
        name: ci-helper-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
